##########################################
# SERVICES
##########################################

# Redis service
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
---
# Postgres service
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
---
# RSTUF API service
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rstuf-api
  name: rstuf-api
spec:
  type: LoadBalancer
  ports:
    - name: "443"
      port: 443
      targetPort: 8443
  selector:
    io.kompose.service: api-gateway
status:
  loadBalancer: {}

# RSTUF Worker is not a service, only a consumer backend
